apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-app
  name: udaconnect-app
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    service: udaconnect-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-app
  name: udaconnect-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-app
  template:
    metadata:
      labels:
        service: udaconnect-app
    spec:
      containers:
      - image: humamilisic/nd064-udaconnect-frontend:e941308c004052edd389ca7a603e9dfaf06cda8b
        name: udaconnect-app
        imagePullPolicy: IfNotPresent
        env:
          - name: REACT_APP_API_KEY
            value: "olaaaaaaaaaaaaaaaaaaaaaaaaaaaa env file radi"
          - name: REACT_APP_REST_API_PERSONS
            value: 'http://localhost:30002/api/persons'
          - name: REACT_APP_REST_API_CONNECTIONS
            value: 'http://localhost:30002/api/persons'
        resources:
          requests:
            memory: "128Mi"
            cpu: "64m"
          limits:
            memory: "256Mi"
            cpu: "256m"
      restartPolicy: Always
